export const MAP = {
  USD: 'USD',
  CAD: 'CAD',
  EUR: 'EUR',
  AED: 'AED',
  AFN: 'AFN',
  ALL: 'ALL',
  AMD: 'AMD',
  ARS: 'ARS',
  AUD: 'AUD',
  AZN: 'AZN',
  BAM: 'BAM',
  BDT: 'BDT',
  BGN: 'BGN',
  BHD: 'BHD',
  BIF: 'BIF',
  BND: 'BND',
  BOB: 'BOB',
  BRL: 'BRL',
  BWP: 'BWP',
  BYR: 'BYR',
  BZD: 'BZD',
  CDF: 'CDF',
  CHF: 'CHF',
  CLP: 'CLP',
  CNY: 'CNY',
  COP: 'COP',
  CRC: 'CRC',
  CVE: 'CVE',
  CZK: 'CZK',
  DJF: 'DJF',
  DKK: 'DKK',
  DOP: 'DOP',
  DZD: 'DZD',
  EEK: 'EEK',
  EGP: 'EGP',
  ERN: 'ERN',
  ETB: 'ETB',
  GBP: 'GBP',
  GEL: 'GEL',
  GHS: 'GHS',
  GNF: 'GNF',
  GTQ: 'GTQ',
  HKD: 'HKD',
  HNL: 'HNL',
  HRK: 'HRK',
  HUF: 'HUF',
  IDR: 'IDR',
  ILS: 'ILS',
  INR: 'INR',
  IQD: 'IQD',
  IRR: 'IRR',
  ISK: 'ISK',
  JMD: 'JMD',
  JOD: 'JOD',
  JPY: 'JPY',
  KES: 'KES',
  KHR: 'KHR',
  KMF: 'KMF',
  KRW: 'KRW',
  KWD: 'KWD',
  KZT: 'KZT',
  LBP: 'LBP',
  LKR: 'LKR',
  LTL: 'LTL',
  LVL: 'LVL',
  LYD: 'LYD',
  MAD: 'MAD',
  MDL: 'MDL',
  MGA: 'MGA',
  MKD: 'MKD',
  MMK: 'MMK',
  MOP: 'MOP',
  MUR: 'MUR',
  MXN: 'MXN',
  MYR: 'MYR',
  MZN: 'MZN',
  NAD: 'NAD',
  NGN: 'NGN',
  NIO: 'NIO',
  NOK: 'NOK',
  NPR: 'NPR',
  NZD: 'NZD',
  OMR: 'OMR',
  PAB: 'PAB',
  PEN: 'PEN',
  PHP: 'PHP',
  PKR: 'PKR',
  PLN: 'PLN',
  PYG: 'PYG',
  QAR: 'QAR',
  RON: 'RON',
  RSD: 'RSD',
  RUB: 'RUB',
  RWF: 'RWF',
  SAR: 'SAR',
  SDG: 'SDG',
  SEK: 'SEK',
  SGD: 'SGD',
  SOS: 'SOS',
  SYP: 'SYP',
  THB: 'THB',
  TND: 'TND',
  TOP: 'TOP',
  TRY: 'TRY',
  TTD: 'TTD',
  TWD: 'TWD',
  TZS: 'TZS',
  UAH: 'UAH',
  UGX: 'UGX',
  UYU: 'UYU',
  UZS: 'UZS',
  VEF: 'VEF',
  VND: 'VND',
  XAF: 'XAF',
  XOF: 'XOF',
  YER: 'YER',
  ZAR: 'ZAR',
  ZMK: 'ZMK',
};

export const LIST = [
  { value: 'USD', key: 'USD' },
  { value: 'CAD', key: 'CAD' },
  { value: 'EUR', key: 'EUR' },
  { value: 'AED', key: 'AED' },
  { value: 'AFN', key: 'AFN' },
  { value: 'ALL', key: 'ALL' },
  { value: 'AMD', key: 'AMD' },
  { value: 'ARS', key: 'ARS' },
  { value: 'AUD', key: 'AUD' },
  { value: 'AZN', key: 'AZN' },
  { value: 'BAM', key: 'BAM' },
  { value: 'BDT', key: 'BDT' },
  { value: 'BGN', key: 'BGN' },
  { value: 'BHD', key: 'BHD' },
  { value: 'BIF', key: 'BIF' },
  { value: 'BND', key: 'BND' },
  { value: 'BOB', key: 'BOB' },
  { value: 'BRL', key: 'BRL' },
  { value: 'BWP', key: 'BWP' },
  { value: 'BYR', key: 'BYR' },
  { value: 'BZD', key: 'BZD' },
  { value: 'CDF', key: 'CDF' },
  { value: 'CHF', key: 'CHF' },
  { value: 'CLP', key: 'CLP' },
  { value: 'CNY', key: 'CNY' },
  { value: 'COP', key: 'COP' },
  { value: 'CRC', key: 'CRC' },
  { value: 'CVE', key: 'CVE' },
  { value: 'CZK', key: 'CZK' },
  { value: 'DJF', key: 'DJF' },
  { value: 'DKK', key: 'DKK' },
  { value: 'DOP', key: 'DOP' },
  { value: 'DZD', key: 'DZD' },
  { value: 'EEK', key: 'EEK' },
  { value: 'EGP', key: 'EGP' },
  { value: 'ERN', key: 'ERN' },
  { value: 'ETB', key: 'ETB' },
  { value: 'GBP', key: 'GBP' },
  { value: 'GEL', key: 'GEL' },
  { value: 'GHS', key: 'GHS' },
  { value: 'GNF', key: 'GNF' },
  { value: 'GTQ', key: 'GTQ' },
  { value: 'HKD', key: 'HKD' },
  { value: 'HNL', key: 'HNL' },
  { value: 'HRK', key: 'HRK' },
  { value: 'HUF', key: 'HUF' },
  { value: 'IDR', key: 'IDR' },
  { value: 'ILS', key: 'ILS' },
  { value: 'INR', key: 'INR' },
  { value: 'IQD', key: 'IQD' },
  { value: 'IRR', key: 'IRR' },
  { value: 'ISK', key: 'ISK' },
  { value: 'JMD', key: 'JMD' },
  { value: 'JOD', key: 'JOD' },
  { value: 'JPY', key: 'JPY' },
  { value: 'KES', key: 'KES' },
  { value: 'KHR', key: 'KHR' },
  { value: 'KMF', key: 'KMF' },
  { value: 'KRW', key: 'KRW' },
  { value: 'KWD', key: 'KWD' },
  { value: 'KZT', key: 'KZT' },
  { value: 'LBP', key: 'LBP' },
  { value: 'LKR', key: 'LKR' },
  { value: 'LTL', key: 'LTL' },
  { value: 'LVL', key: 'LVL' },
  { value: 'LYD', key: 'LYD' },
  { value: 'MAD', key: 'MAD' },
  { value: 'MDL', key: 'MDL' },
  { value: 'MGA', key: 'MGA' },
  { value: 'MKD', key: 'MKD' },
  { value: 'MMK', key: 'MMK' },
  { value: 'MOP', key: 'MOP' },
  { value: 'MUR', key: 'MUR' },
  { value: 'MXN', key: 'MXN' },
  { value: 'MYR', key: 'MYR' },
  { value: 'MZN', key: 'MZN' },
  { value: 'NAD', key: 'NAD' },
  { value: 'NGN', key: 'NGN' },
  { value: 'NIO', key: 'NIO' },
  { value: 'NOK', key: 'NOK' },
  { value: 'NPR', key: 'NPR' },
  { value: 'NZD', key: 'NZD' },
  { value: 'OMR', key: 'OMR' },
  { value: 'PAB', key: 'PAB' },
  { value: 'PEN', key: 'PEN' },
  { value: 'PHP', key: 'PHP' },
  { value: 'PKR', key: 'PKR' },
  { value: 'PLN', key: 'PLN' },
  { value: 'PYG', key: 'PYG' },
  { value: 'QAR', key: 'QAR' },
  { value: 'RON', key: 'RON' },
  { value: 'RSD', key: 'RSD' },
  { value: 'RUB', key: 'RUB' },
  { value: 'RWF', key: 'RWF' },
  { value: 'SAR', key: 'SAR' },
  { value: 'SDG', key: 'SDG' },
  { value: 'SEK', key: 'SEK' },
  { value: 'SGD', key: 'SGD' },
  { value: 'SOS', key: 'SOS' },
  { value: 'SYP', key: 'SYP' },
  { value: 'THB', key: 'THB' },
  { value: 'TND', key: 'TND' },
  { value: 'TOP', key: 'TOP' },
  { value: 'TRY', key: 'TRY' },
  { value: 'TTD', key: 'TTD' },
  { value: 'TWD', key: 'TWD' },
  { value: 'TZS', key: 'TZS' },
  { value: 'UAH', key: 'UAH' },
  { value: 'UGX', key: 'UGX' },
  { value: 'UYU', key: 'UYU' },
  { value: 'UZS', key: 'UZS' },
  { value: 'VEF', key: 'VEF' },
  { value: 'VND', key: 'VND' },
  { value: 'XAF', key: 'XAF' },
  { value: 'XOF', key: 'XOF' },
  { value: 'YER', key: 'YER' },
  { value: 'ZAR', key: 'ZAR' },
  { value: 'ZMK', key: 'ZMK' },
];
