import type { Item } from './limited-users.types';

export const data: Item[] = [
  {
    id: 'layout',
    name: 'Layout',
    type: 'group',
    children: [
      {
        id: 'multiPageForms',
        name: 'Create Multi-page forms',
        type: 'boolean',
        enabled: true,
      },
      {
        id: 'fieldTypes',
        name: 'Allowed Field Types',
        type: 'toggles',
        values: ['text', 'textarea', 'hidden'],
        options: [
          { value: 'text', label: 'Text' },
          { value: 'textarea', label: 'Textarea' },
          { value: 'email', label: 'Email' },
          { value: 'hidden', label: 'Hidden' },
          { value: 'dropdown', label: 'Dropdown' },
          { value: 'multiselect', label: 'Multi-select' },
          { value: 'checkbox', label: 'Checkbox' },
          { value: 'checkboxes', label: 'Checkboxes' },
          { value: 'radios', label: 'Radios' },
          { value: 'fileUpload', label: 'FileUpload' },
          { value: 'fileDnD', label: 'File Drag & Drop' },
          { value: 'number', label: 'Number' },
          { value: 'confirm', label: 'Confirm' },
          { value: 'dateAndTime', label: 'Date & Time' },
          { value: 'password', label: 'Password' },
          { value: 'phone', label: 'Phone' },
          { value: 'rating', label: 'Rating' },
          { value: 'regex', label: 'Regex' },
          { value: 'website', label: 'Website' },
          { value: 'opinionScale', label: 'Opinion Scale' },
          { value: 'signature', label: 'Signature' },
          { value: 'table', label: 'Table' },
          { value: 'invisible', label: 'Invisible' },
          { value: 'html', label: 'HTML' },
          { value: 'richText', label: 'Rich Text' },
          { value: 'group', label: 'Group' },
        ],
      },
      {
        id: 'maxColumns',
        name: 'Maximum Fields Per Row',
        type: 'select',
        value: '4',
        options: [
          { value: '1', label: '1' },
          { value: '2', label: '2' },
          { value: '3', label: '3' },
          { value: '4', label: '4' },
        ],
      },
      {
        id: 'fields',
        name: 'Field Properties',
        type: 'group',
        children: [
          {
            id: 'handles',
            name: 'Field Handles',
            type: 'boolean',
            enabled: true,
          },
          {
            id: 'attributes',
            name: 'Field Attribute Editor',
            type: 'boolean',
            enabled: true,
          },
          {
            id: 'types',
            name: 'Field Type Switcher',
            type: 'boolean',
            enabled: false,
          },
        ],
      },
      {
        id: 'options',
        name: 'Field Option Sources',
        type: 'group',
        children: [
          {
            id: 'custom',
            name: 'Custom Options',
            type: 'boolean',
            enabled: true,
          },
          {
            id: 'elements',
            name: 'Elements',
            type: 'boolean',
            enabled: false,
            children: [
              {
                id: 'types',
                name: 'Allowed Types',
                type: 'toggles',
                values: ['entries', 'categories', 'users'],
                options: [
                  { value: 'entries', label: 'Entries' },
                  { value: 'categories', label: 'Categories' },
                  { value: 'tags', label: 'Tags' },
                  { value: 'users', label: 'Users' },
                  { value: 'assets', label: 'Assets' },
                  { value: 'commerce', label: 'Commerce' },
                ],
              },
            ],
          },
          {
            id: 'predefined',
            name: 'Predefined',
            type: 'boolean',
            enabled: true,
            children: [
              {
                id: 'types',
                name: 'Allowed Types',
                type: 'toggles',
                values: ['states', 'languages'],
                options: [
                  { value: 'states', label: 'States' },
                  { value: 'provinces', label: 'Provinces' },
                  { value: 'countries', label: 'Countries' },
                  { value: 'languages', label: 'Languages' },
                  { value: 'currencies', label: 'Currencies' },
                  { value: 'numbers', label: 'Numbers' },
                  { value: 'years', label: 'Years' },
                  { value: 'months', label: 'Months' },
                  { value: 'days', label: 'Days' },
                  { value: 'daysOfWeek', label: 'Days of Week' },
                ],
              },
            ],
          },
          {
            id: 'convertToCustom',
            name: 'Convert to Custom Values (for Element and Predefined populators)',
            type: 'boolean',
            enabled: true,
          },
        ],
      },
    ],
  },
  {
    id: 'notifications',
    name: 'Notifications',
    type: 'group',
    children: [
      {
        id: 'tab',
        name: 'Notifications tab',
        type: 'boolean',
        enabled: true,
        children: [
          {
            id: 'admin',
            name: 'Admin',
            type: 'boolean',
            enabled: true,
          },
          {
            id: 'conditional',
            name: 'Conditional',
            type: 'boolean',
            enabled: false,
          },
          {
            id: 'user',
            name: 'User Select',
            type: 'boolean',
            enabled: false,
          },
          {
            id: 'email',
            name: 'Email',
            type: 'boolean',
            enabled: true,
          },
        ],
      },
    ],
  },
  {
    id: 'rules',
    name: 'Rules',
    type: 'group',
    children: [
      {
        id: 'tab',
        name: 'Rules tab',
        type: 'boolean',
        enabled: false,
        children: [
          {
            id: 'fields',
            name: 'Rules on Fields',
            type: 'boolean',
            enabled: true,
          },
          {
            id: 'buttons',
            name: 'Rules on Buttons',
            type: 'boolean',
            enabled: false,
          },
          {
            id: 'pages',
            name: 'Rules on Pages',
            type: 'boolean',
            enabled: false,
          },
        ],
      },
    ],
  },
  {
    id: 'integrations',
    name: 'Integrations',
    type: 'group',
    children: [
      {
        id: 'tab',
        name: 'Integrations tab',
        type: 'boolean',
        enabled: true,
      },
    ],
  },
  {
    id: 'settings',
    name: 'Settings',
    type: 'group',
    children: [
      {
        id: 'tab',
        name: 'Settings tab',
        type: 'boolean',
        enabled: true,
        children: [
          {
            id: 'general',
            name: 'General',
            type: 'boolean',
            enabled: true,
            children: [
              {
                id: 'handle',
                name: 'Form Handle',
                type: 'boolean',
                enabled: true,
              },
              {
                id: 'type',
                name: 'Form Type',
                type: 'boolean',
                enabled: true,
              },
              {
                id: 'submissionTitle',
                name: 'Submission Title',
                type: 'boolean',
                enabled: true,
              },
              {
                id: 'formattingTemplate',
                name: 'Formatting Template',
                type: 'boolean',
                enabled: true,
              },
            ],
          },
          {
            id: 'dataStorage',
            name: 'Data Storage',
            type: 'boolean',
            enabled: true,
          },
          {
            id: 'processing',
            name: 'Processing',
            type: 'boolean',
            enabled: true,
          },
          {
            id: 'successAndErrors',
            name: 'Success & Errors',
            type: 'boolean',
            enabled: true,
          },
          {
            id: 'limits',
            name: 'Limits',
            type: 'boolean',
            enabled: true,
          },
        ],
      },
    ],
  },
];
