packages:
  - "packages/*"
  - "packages/frontend/*"
  - "packages/frontend/themes/*"

overrides:
  "monaco-editor>dompurify": "3.4.11"
  "brace-expansion": "5.0.6"
  "jsdom>undici": "7.28.0"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "core-js-pure"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

minimumReleaseAgeExclude:
  - react-router-dom@7.18.1
  - react-router@7.18.1
