// Composer
export const ADD_FIELD_TO_NEW_ROW = 'ADD_FIELD_TO_NEW_ROW';
export const REPOSITION_COLUMN = 'REPOSITION_COLUMN';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const FIELD_POSITION_CHANGED = 'FIELD_POSITION_CHANGED';
export const ADD_COLUMN_TO_ROW = 'ADD_COLUMN_TO_ROW';
export const ADD_COLUMN_TO_NEW_ROW = 'ADD_COLUMN_TO_NEW_ROW';

export const SWITCH_PAGE = 'SWITCH_PAGE';
export const SWITCH_HASH = 'SWITCH_HASH';
export const ADD_PAGE = 'ADD_PAGE';
export const REMOVE_PAGE = 'REMOVE_PAGE';

// Properties
export const PROPERTIES_UPDATED = 'PROPERTIES_UPDATED';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const REMOVE_PROPERTY = 'REMOVE_PROPERTY';
export const RESET_PROPERTIES = 'RESET_PROPERTIES';

export const UPDATE_FORM_ID = 'UPDATE_FORM_ID';
export const UPDATE_DUPLICATE_HANDLE_LIST = 'UPDATE_DUPLICATE_HANDLE_LIST';

export const ADD_VALUE_SET = 'ADD_VALUE_SET';
export const CLEAN_UP_VALUES = 'CLEAN_UP_VALUES';
export const UPDATE_VALUE_SET = 'UPDATE_VALUE_SET';
export const UPDATE_IS_CHECKED = 'UPDATE_IS_CHECKED';
export const INSERT_VALUE = 'INSERT_VALUE';
export const REMOVE_VALUE = 'REMOVE_VALUE';
export const TOGGLE_CUSTOM_VALUES = 'TOGGLE_CUSTOM_VALUES';
export const REORDER_VALUE_SET = 'REORDER_VALUE_SET';
export const REMOVE_VALUE_SET = 'REMOVE_VALUE_SET';

export const MATRIX_ADD_ROW = 'MATRIX_ADD_ROW';
export const MATRIX_REMOVE_ROW = 'MATRIX_REMOVE_ROW';
export const MATRIX_SWAP_ROW = 'MATRIX_SWAP_ROW';
export const MATRIX_UPDATE_COLUMN = 'MATRIX_UPDATE_COLUMN';

// Fields
export const REQUEST_FIELDS = 'REQUEST_FIELDS';
export const RECEIVE_FIELDS = 'RECEIVE_FIELDS';
export const INVALIDATE_FIELDS = 'INVALIDATE_FIELDS';

// Notifications
export const REQUEST_NOTIFICATIONS = 'REQUEST_NOTIFICATIONS';
export const RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS';
export const INVALIDATE_NOTIFICATIONS = 'INVALIDATE_NOTIFICATIONS';

// Form Templates
export const REQUEST_FORM_TEMPLATES = 'REQUEST_FORM_TEMPLATES';
export const RECEIVE_FORM_TEMPLATES = 'RECEIVE_FORM_TEMPLATES';
export const INVALIDATE_FORM_TEMPLATES = 'INVALIDATE_FORM_TEMPLATES';

// Mailing Lists
export const REQUEST_MAILING_LISTS = 'REQUEST_MAILING_LISTS';
export const RECEIVE_MAILING_LISTS = 'RECEIVE_MAILING_LISTS';
export const INVALIDATE_MAILING_LISTS = 'INVALIDATE_MAILING_LISTS';

// List Source Targets
export const REQUEST_GENERATED_OPTIONS = 'REQUEST_GENERATED_OPTIONS';
export const RECEIVE_GENERATED_OPTIONS = 'RECEIVE_GENERATED_OPTIONS';
export const INVALIDATE_GENERATED_OPTIONS = 'INVALIDATE_GENERATED_OPTIONS';

// CRM Integrations
export const REQUEST_CRM_INTEGRATIONS = 'REQUEST_CRM_INTEGRATIONS';
export const RECEIVE_CRM_INTEGRATIONS = 'RECEIVE_CRM_INTEGRATIONS';
export const INVALIDATE_CRM_INTEGRATIONS = 'INVALIDATE_CRM_INTEGRATIONS';
export const END_REQUEST_CRM_INTEGRATIONS = 'END_REQUEST_CRM_INTEGRATIONS';

// Paymen Gateways
export const REQUEST_PAYMENT_GATEWAYS = 'REQUEST_PAYMENT_GATEWAYS';
export const RECEIVE_PAYMENT_GATEWAYS = 'RECEIVE_PAYMENT_GATEWAYS';
export const INVALIDATE_PAYMENT_GATEWAYS = 'INVALIDATE_PAYMENT_GATEWAYS';
export const END_REQUEST_PAYMENT_GATEWAYS = 'END_REQUEST_PAYMENT_GATEWAYS';
export const CREATE_PAYMENT_PLAN = 'CREATE_PAYMENT_PLAN';
export const END_CREATE_PAYMENT_PLAN = 'END_CREATE_PAYMENT_PLAN';
export const REQUEST_PAYMENT_PLANS = 'REQUEST_PAYMENT_PLANS';
export const RECEIVE_PAYMENT_PLANS = 'RECEIVE_PAYMENT_PLANS';
export const INVALIDATE_PAYMENT_PLANS = 'INVALIDATE_PAYMENT_PLANS';

// Connections
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';
export const UPDATE_CONNECTION = 'UPDATE_CONNECTION';

// Rules
export const ADD_PAGE_BLOCK = 'ADD_PAGE_BLOCK';
export const REMOVE_PAGE_BLOCK = 'REMOVE_PAGE_BLOCK';
export const ADD_FIELD_RULE = 'ADD_FIELD_RULE';
export const REMOVE_FIELD_RULE = 'REMOVE_FIELD_RULE';
export const ADD_GOTO_RULE = 'ADD_GOTO_RULE';
export const REMOVE_GOTO_RULE = 'REMOVE_GOTO_RULE';
export const TOGGLE_FIELD_RULE_SHOW = 'TOGGLE_FIELD_RULE_SHOW';
export const TOGGLE_RULE_MATCH_ALL = 'TOGGLE_RULE_MATCH_ALL';
export const ADD_RULE_CRITERIA = 'ADD_RULE_CRITERIA';
export const REMOVE_RULE_CRITERIA = 'REMOVE_RULE_CRITERIA';
export const UPDATE_RULE_CRITERIA_HASH = 'UPDATE_RULE_CRITERIA_HASH';
export const TOGGLE_RULE_CRITERIA_EQUALS = 'TOGGLE_RULE_CRITERIA_EQUALS';
export const UPDATE_RULE_CRITERIA_VALUE = 'UPDATE_RULE_CRITERIA_VALUE';

// Placeholders
export const ADD_PLACEHOLDER_ROW = 'ADD_PLACEHOLDER_ROW';
export const ADD_PLACEHOLDER_COLUMN = 'ADD_PLACEHOLDER_COLUMN';
export const ADD_PLACEHOLDER_PAGE = 'ADD_PLACEHOLDER_PAGE';
export const CLEAR_PLACEHOLDERS = 'CLEAR_PLACEHOLDERS';

// Pages
export const SWAP_PAGE = 'SWAP_PAGE';
