name: Builder

permissions:
  contents: read

on:
  pull_request:
    branches: [v5]

jobs:
  ts-linter:
    runs-on: ubuntu-latest
    name: Linter

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: pnpm lint
        run: pnpm --filter @ff/client lint

  ts-tests:
    runs-on: ubuntu-latest
    name: Tests

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: pnpm test
        run: pnpm --filter @ff/client test
